version: "3.8"

services:
  flask:
    build: .
    environment:
      - FLASK_APP=application
      - FLASK_DEBUG=1
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    ports:
      - 5000:5000
    volumes:
      - ./app:/src/app
    networks:
      - database

  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - database

networks:
  database:
    driver: bridge
