version: '3.8'

services:
  web:
    environment:
      - FLASK_APP=application
      - FLASK_DEBUG=1
      - FLASK_CONFIG=development
    ports:
      - ${FLASK_PORT}:${FLASK_PORT}
    volumes:
      - ./flask-app:/src
